const Languages = {
  BELARUSIAN: { name: 'Belarusian', code: 'be' },
  CATALAN: { name: 'Catalan', code: 'ca' },
  CZECH: { name: 'Czech', code: 'cs' },
  DANISH: { name: 'Danish', code: 'da' },
  GERMAN: { name: 'German', code: 'de' },
  GREEK: { name: 'Greek', code: 'el' },
  ENGLISH: { name: 'English', code: 'en' },
  SPANISH: { name: 'Spanish', code: 'es' },
  FRENCH: { name: 'French', code: 'fr' },
  HUNGARIAN: { name: 'Hungarian', code: 'hu' },
  ARMENIAN: { name: 'Armenian', code: 'hy' },
  ITALIAN: { name: 'Italian', code: 'it' },
  KOREAN: { name: 'Korean', code: 'ko' },
  LATVIAN: { name: 'Latvian', code: 'lv' },
  DUTCH: { name: 'Dutch', code: 'nl' },
  JAPANESE: { name: 'Japanese', code: 'ja' },
  POLISH: { name: 'Polish', code: 'pl' },
  PORTUGUESE: { name: 'Portuguese', code: 'pt' },
  RUSSIAN: { name: 'Russian', code: 'ru' },
  SERBIAN: { name: 'Serbian', code: 'sr' },
  FINNISH: { name: 'Finnish', code: 'fi' },
  SWEDISH: { name: 'Swedish', code: 'sv' },
  TURKISH: { name: 'Turkish', code: 'tr' },
  UKRAINIAN: { name: 'Ukrainian', code: 'uk' },
  CHINESE: { name: 'Chinese', code: 'zh' },
}

export default Languages
